/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XpartlaAmbulanceWlList {
    }
}
declare global {
    interface HTMLXpartlaAmbulanceWlListElement extends Components.XpartlaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXpartlaAmbulanceWlListElement: {
        prototype: HTMLXpartlaAmbulanceWlListElement;
        new (): HTMLXpartlaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xpartla-ambulance-wl-list": HTMLXpartlaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XpartlaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xpartla-ambulance-wl-list": XpartlaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xpartla-ambulance-wl-list": LocalJSX.IntrinsicElements["xpartla-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLXpartlaAmbulanceWlListElement>;
        }
    }
}
